# Generated by Django 4.1.1 on 2022-12-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='family',
            new_name='pokemon',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='name',
            new_name='pokemon_type',
        ),
    ]
